### ISSUE TITLE
i am getting sqlciper issue with this library on older device

### ISSUE THREAD

**Issue by deepeshalways** [itext/itextpdf#13]
05-04 12:40:36.108 10605-10605/com****.**** E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.****.**** PID: 10605
                                                                 java.lang.VerifyError:net/sqlcipher/database/SQLiteDatabase                                                                     

Whenever i am running app with this library it gives this Verify error but without this liibrary app runs easy...and this problem is coming in 4.4 and lower devices.

**Comment by amedee** [comment]
For Professional Support, please see http://itextpdf.com/support
For Community Support, please ask your question on StackOverflow: http://stackoverflow.com/questions/tagged/itextpdf

**Comment by deepeshalways** [comment]
Can't you answer here as i want to check that it work for all devices or not...if it works then i will purchase it otherwise why i waste my money on it...and i have already asked que about this on stackoverflow but no support

**Comment by amedee** [comment]
Please give the link to your answer on Stack Overflow.

**Comment by amedee** [comment]
Please give the link to your question on Stack Overflow.

**Comment by michaeldemey** [comment]
"java.lang.VerifyError can be the result when you have compiled against a different library than you are using at runtime."

~http://stackoverflow.com/questions/100107/reasons-of-getting-a-java-lang-verifyerror

You probably compiled with a different version than the one that's available on the classpath. Make sure your versions of SQLite are the same. I assume that because this issue pops up with Android 4.4 and lower you've compiled against a newer SQLite version than the one bundled in those Android versions:

http://stackoverflow.com/questions/2421189/version-of-sqlite-used-in-android

**Comment by deepeshalways** [comment]
@amedee  here is the link

http://stackoverflow.com/questions/37024666/getting-verify-error-for-sqlcipher-in-android-with-itext-lib
